
##############################################################
# This Script has been generated by Ixia ScriptGen
#      Software Version : IxOS 8.01.1213.5 EA         
##############################################################


package req IxTclHal

# Command Option Mode - Full (generate full configuration)


if {[isUNIX]} {
	if {[ixConnectToTclServer 172.16.174.131]} {
		errorMsg "Error connecting to Tcl Server 172.16.174.131 "
		return $::TCL_ERROR
	}
}

######### Chassis list - {172.16.174.131} #########

ixConnectToChassis   {172.16.174.131}

set owner "ixia"
ixLogin $owner

set portList {}



######### Chassis-172.16.174.131 #########

chassis get "172.16.174.131"
set chassis	  [chassis cget -id]

######### Card Type : Ixia Virtual Load Module ############

set card     1

######### Chassis-172.16.174.131 Card-1  Port-1 #########

set port     1

port setFactoryDefaults $chassis $card $port
port config -speed                              1000
port config -duplex                             full
port config -flowControl                        false
port config -directedAddress                    "01 80 C2 00 00 01"
port config -multicastPauseAddress              "01 80 C2 00 00 01"
port config -loopback                           portNormal
port config -transmitMode                       portTxPacketStreams
port config -receiveMode                        [expr $::portCapture|$::portRxModeWidePacketGroup]
port config -autonegotiate                      false
port config -advertise100FullDuplex             false
port config -advertise100HalfDuplex             false
port config -advertise10FullDuplex              false
port config -advertise10HalfDuplex              false
port config -advertise1000FullDuplex            false
port config -portMode                           portEthernetMode
port config -enableDataCenterMode               false
port config -dataCenterMode                     eightPriorityTrafficMapping
port config -flowControlType                    ieee8023x
port config -pfcEnableValueListBitMatrix        ""
port config -pfcResponseDelayEnabled            0
port config -pfcResponseDelayQuanta             0
port config -rxTxMode                           gigNormal
port config -ignoreLink                         false
port config -advertiseAbilities                 portAdvertiseNone
port config -timeoutEnable                      true
port config -negotiateMasterSlave               0
port config -masterSlave                        portSlave
port config -pmaClock                           pmaClockAutoNegotiate
port config -enableSimulateCableDisconnect      false
port config -enableAutoDetectInstrumentation    false
port config -autoDetectInstrumentationMode      portAutoInstrumentationModeEndOfFrame
port config -enableRepeatableLastRandomPattern  false
port config -transmitClockDeviation             0
port config -transmitClockMode                  portClockInternal
port config -preEmphasis                        preEmphasis0
port config -transmitExtendedTimestamp          0
port config -operationModeList                  [list]
port config -MacAddress                         "00 de bb 00 00 01"
port config -DestMacAddress                     "00 de bb 00 00 02"
port config -name                               ""
port config -numAddresses                       1
port config -enableManualAutoNegotiate          false
port config -enablePhyPolling                   true
port config -enableTxRxSyncStatsMode            false
port config -txRxSyncInterval                   0
port config -enableTransparentDynamicRateChange false
port config -enableDynamicMPLSMode              false
port config -enablePortCpuFlowControl           false
port config -portCpuFlowControlDestAddr         "01 80 C2 00 00 01"
port config -portCpuFlowControlSrcAddr          "00 00 01 00 02 00"
port config -portCpuFlowControlPriority         "0 0 0 0 0 0 0 0"
port config -portCpuFlowControlType             0
port config -enableWanIFSStretch                false
port config -enableRestartStream                false
port config -enableRxNonIEEEPreamble            false
port config -enableRsFec                        false
port config -enableRsFecStats                   false
port config -enableLinkTraining                 false
port config -ieeeL1Defaults                     0
if {[port set $chassis $card $port]} {
	errorMsg "Error calling port set $chassis $card $port"
	set retCode $::TCL_ERROR
}

stat setDefault 
stat config -mode                               statNormal
stat config -enableValidStats                   false
stat config -enableProtocolServerStats          true
stat config -enableArpStats                     true
stat config -enablePosExtendedStats             true
stat config -enableDhcpStats                    false
stat config -enableDhcpV6Stats                  false
stat config -enableEthernetOamStats             false
stat config -enableFcoeStats                    false
stat config -fcoeRxSharedStatType1              statFcoeValidFrames
stat config -fcoeRxSharedStatType2              statFcoeValidFrames
stat config -enableLldpDcbxStats                false
stat config -enableBgpStats                     false
stat config -enableIcmpStats                    true
stat config -enableOspfStats                    false
stat config -enableIsisStats                    false
stat config -enableRsvpStats                    false
stat config -enableLdpStats                     false
stat config -enableIgmpStats                    false
stat config -enableOspfV3Stats                  false
stat config -enablePimsmStats                   false
stat config -enableMldStats                     false
stat config -enableStpStats                     false
stat config -enableEigrpStats                   false
stat config -enableBfdStats                     false
stat config -enableCfmStats                     false
stat config -enableLacpStats                    false
stat config -enableOamStats                     false
stat config -enableMplsTpStats                  false
stat config -enableElmiStats                    false
if {[stat set $chassis $card $port]} {
	errorMsg "Error calling stat set $chassis $card $port"
	set retCode $::TCL_ERROR
}

packetGroup setDefault 
packetGroup config -signatureOffset                    48
packetGroup config -signature                          "08 71 18 05"
packetGroup config -insertSignature                    false
packetGroup config -ignoreSignature                    false
packetGroup config -groupId                            0
packetGroup config -groupIdOffset                      52
packetGroup config -enableGroupIdMask                  false
packetGroup config -enableInsertPgid                   true
packetGroup config -groupIdMask                        0
packetGroup config -latencyControl                     cutThrough
packetGroup config -measurementMode                    packetGroupModeLatency
packetGroup config -preambleSize                       8
packetGroup config -sequenceNumberOffset               44
packetGroup config -sequenceErrorThreshold             2
packetGroup config -insertSequenceSignature            false
packetGroup config -allocateUdf                        true
packetGroup config -enableSignatureMask                false
packetGroup config -signatureMask                      "00 00 00 00"
packetGroup config -enableRxFilter                     false
packetGroup config -headerFilter                       "00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"
packetGroup config -headerFilterMask                   "00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"
packetGroup config -enable128kBinMode                  false
packetGroup config -enableTimeBins                     false
packetGroup config -numPgidPerTimeBin                  32
packetGroup config -numTimeBins                        1
packetGroup config -timeBinDuration                    1000000
packetGroup config -enableLatencyBins                  false
packetGroup config -latencyBinList                     ""
packetGroup config -groupIdMode                        packetGroupCustom
packetGroup config -sequenceCheckingMode               seqThreshold
packetGroup config -multiSwitchedPathMode              seqSwitchedPathPGID
packetGroup config -pgidStatMode                       0
packetGroup config -enableLastBitTimeStamp             false
packetGroup config -seqAdvTrackingLateThreshold        1000
packetGroup config -enableReArmFirstTimeStamp          false
if {[packetGroup setRx $chassis $card $port]} {
	errorMsg "Error calling packetGroup setRx $chassis $card $port"
	set retCode $::TCL_ERROR
}


filter setDefault 
filter config -captureTriggerDA                   anyAddr
filter config -captureTriggerSA                   anyAddr
filter config -captureTriggerPattern              anyPattern
filter config -captureTriggerError                errAnyFrame
filter config -captureTriggerFrameSizeEnable      false
filter config -captureTriggerFrameSizeFrom        0
filter config -captureTriggerFrameSizeTo          0
filter config -captureTriggerCircuit              filterAnyCircuit
filter config -captureFilterDA                    anyAddr
filter config -captureFilterSA                    anyAddr
filter config -captureFilterPattern               anyPattern
filter config -captureFilterError                 errAnyFrame
filter config -captureFilterFrameSizeEnable       false
filter config -captureFilterFrameSizeFrom         0
filter config -captureFilterFrameSizeTo           0
filter config -captureFilterCircuit               filterAnyCircuit
filter config -userDefinedStat1DA                 anyAddr
filter config -userDefinedStat1SA                 anyAddr
filter config -userDefinedStat1Pattern            anyPattern
filter config -userDefinedStat1Error              errAnyFrame
filter config -userDefinedStat1FrameSizeEnable    false
filter config -userDefinedStat1FrameSizeFrom      0
filter config -userDefinedStat1FrameSizeTo        0
filter config -userDefinedStat1Circuit            filterAnyCircuit
filter config -userDefinedStat2DA                 anyAddr
filter config -userDefinedStat2SA                 anyAddr
filter config -userDefinedStat2Pattern            anyPattern
filter config -userDefinedStat2Error              errAnyFrame
filter config -userDefinedStat2FrameSizeEnable    0
filter config -userDefinedStat2FrameSizeFrom      0
filter config -userDefinedStat2FrameSizeTo        0
filter config -userDefinedStat2Circuit            filterAnyCircuit
filter config -asyncTrigger1DA                    anyAddr
filter config -asyncTrigger1SA                    anyAddr
filter config -asyncTrigger1Pattern               anyPattern
filter config -asyncTrigger1Error                 errAnyFrame
filter config -asyncTrigger1FrameSizeEnable       false
filter config -asyncTrigger1FrameSizeFrom         0
filter config -asyncTrigger1FrameSizeTo           0
filter config -asyncTrigger1Circuit               filterAnyCircuit
filter config -asyncTrigger2DA                    anyAddr
filter config -asyncTrigger2SA                    anyAddr
filter config -asyncTrigger2Pattern               anyPattern
filter config -asyncTrigger2Error                 errAnyFrame
filter config -asyncTrigger2FrameSizeEnable       false
filter config -asyncTrigger2FrameSizeFrom         0
filter config -asyncTrigger2FrameSizeTo           0
filter config -asyncTrigger2Circuit               filterAnyCircuit
filter config -captureTriggerEnable               true
filter config -captureFilterEnable                true
filter config -userDefinedStat1Enable             false
filter config -userDefinedStat2Enable             false
filter config -asyncTrigger1Enable                false
filter config -asyncTrigger2Enable                false
filter config -userDefinedStat1PatternExpressionEnable false
filter config -userDefinedStat2PatternExpressionEnable false
filter config -captureTriggerPatternExpressionEnable false
filter config -captureFilterPatternExpressionEnable false
filter config -asyncTrigger1PatternExpressionEnable false
filter config -asyncTrigger2PatternExpressionEnable false
filter config -userDefinedStat1PatternExpression  ""
filter config -userDefinedStat2PatternExpression  ""
filter config -captureTriggerPatternExpression    ""
filter config -captureFilterPatternExpression     ""
filter config -asyncTrigger1PatternExpression     ""
filter config -asyncTrigger2PatternExpression     ""
if {[filter set $chassis $card $port]} {
	errorMsg "Error calling filter set $chassis $card $port"
	set retCode $::TCL_ERROR
}


filterPallette setDefault 
filterPallette config -DA1                                "00 00 00 00 00 00"
filterPallette config -DAMask1                            "00 00 00 00 00 00"
filterPallette config -DA2                                "00 00 00 00 00 00"
filterPallette config -DAMask2                            "00 00 00 00 00 00"
filterPallette config -SA1                                "00 00 00 00 00 00"
filterPallette config -SAMask1                            "00 00 00 00 00 00"
filterPallette config -SA2                                "00 00 00 00 00 00"
filterPallette config -SAMask2                            "00 00 00 00 00 00"
filterPallette config -pattern1                           "DE ED EF FE AC CA"
filterPallette config -patternMask1                       "00 00 00 00 00 00"
filterPallette config -pattern2                           00
filterPallette config -patternMask2                       00
filterPallette config -pattern3                           ""
filterPallette config -patternMask3                       ""
filterPallette config -pattern4                           ""
filterPallette config -patternMask4                       ""
filterPallette config -patternOffset1                     12
filterPallette config -patternOffset2                     12
filterPallette config -patternOffset3                     0
filterPallette config -patternOffset4                     0
filterPallette config -matchType1                         matchUser
filterPallette config -matchType2                         matchUser
filterPallette config -matchType3                         3
filterPallette config -matchType4                         3
filterPallette config -patternOffsetType1                 filterPalletteOffsetStartOfFrame
filterPallette config -patternOffsetType2                 filterPalletteOffsetStartOfFrame
filterPallette config -patternOffsetType3                 0
filterPallette config -patternOffsetType4                 0
filterPallette config -gfpErrorCondition                  gfpErrorsOr
filterPallette config -enableGfptHecError                 true
filterPallette config -enableGfpeHecError                 true
filterPallette config -enableGfpPayloadCrcError           true
filterPallette config -enableGfpBadFcsError               true
filterPallette config -circuitList                        ""
filterPallette config -range1Min                          0
filterPallette config -range1Max                          0
filterPallette config -range2Min                          0
filterPallette config -range2Max                          0
filterPallette config -range3Min                          0
filterPallette config -range3Max                          0
filterPallette config -range4Min                          0
filterPallette config -range4Max                          0
filterPallette config -range1MatchMinMaxOnly              0
filterPallette config -range2MatchMinMaxOnly              0
filterPallette config -range3MatchMinMaxOnly              0
filterPallette config -range4MatchMinMaxOnly              0
if {[filterPallette set $chassis $card $port]} {
	errorMsg "Error calling filterPallette set $chassis $card $port"
	set retCode $::TCL_ERROR
}


ipAddressTable setDefault 
ipAddressTable config -defaultGateway                     "0.0.0.0"
if {[ipAddressTable set $chassis $card $port]} {
	errorMsg "Error calling ipAddressTable set $chassis $card $port"
	set retCode $::TCL_ERROR
}


if {[interfaceTable select $chassis $card $port]} {
	errorMsg "Error calling interfaceTable select $chassis $card $port"
	set retCode $::TCL_ERROR
}

interfaceTable setDefault 
interfaceTable config -dhcpV4RequestRate                  0
interfaceTable config -dhcpV6RequestRate                  0
interfaceTable config -dhcpV4MaximumOutstandingRequests   100
interfaceTable config -dhcpV6MaximumOutstandingRequests   100
interfaceTable config -fcoeRequestRate                    500
interfaceTable config -fcoeNumRetries                     5
interfaceTable config -fcoeRetryInterval                  2000
interfaceTable config -fipVersion                         fipVersion1
interfaceTable config -enableFcfMac                       false
interfaceTable config -fcfMacCollectionTime               1000
interfaceTable config -enablePMacInFpma                   true
interfaceTable config -enableNameIdInVLANDiscovery        false
interfaceTable config -enableTargetLinkLayerAddrOption    false
interfaceTable config -enableAutoNeighborDiscovery        false
interfaceTable config -enableAutoArp                      false
if {[interfaceTable set]} {
	errorMsg "Error calling interfaceTable set"
	set retCode $::TCL_ERROR
}

interfaceTable clearAllInterfaces 
if {[interfaceTable write]} {
	errorMsg "Error calling interfaceTable write"
	set retCode $::TCL_ERROR
}


protocolServer setDefault 
protocolServer config -enableArpResponse                  false
protocolServer config -enablePingResponse                 false
if {[protocolServer set $chassis $card $port]} {
	errorMsg "Error calling protocolServer set $chassis $card $port"
	set retCode $::TCL_ERROR
}


oamPort setDefault 
oamPort config -enable                             false
oamPort config -macAddress                         "00 00 AB BA DE AD"
oamPort config -enableLoopback                     false
oamPort config -enableLinkEvents                   false
oamPort config -maxOamPduSize                      1518
oamPort config -oui                                "00 00 00"
oamPort config -vendorSpecificInformation          "00 00 00 00"
oamPort config -idleTimer                          5
oamPort config -enableOptionalTlv                  false
oamPort config -optionalTlvType                    254
oamPort config -optionalTlvValue                   ""
if {[oamPort set $chassis $card $port]} {
	errorMsg "Error calling oamPort set $chassis $card $port"
	set retCode $::TCL_ERROR
}

lappend portList [list $chassis $card $port]

######### Card Type : Ixia Virtual Load Module ############

set card     2

######### Chassis-172.16.174.131 Card-2  Port-1 #########

set port     1

port setFactoryDefaults $chassis $card $port
port config -speed                              1000
port config -duplex                             full
port config -flowControl                        false
port config -directedAddress                    "01 80 C2 00 00 01"
port config -multicastPauseAddress              "01 80 C2 00 00 01"
port config -loopback                           portNormal
port config -transmitMode                       portTxPacketStreams
port config -receiveMode                        [expr $::portCapture|$::portRxModeWidePacketGroup]
port config -autonegotiate                      false
port config -advertise100FullDuplex             false
port config -advertise100HalfDuplex             false
port config -advertise10FullDuplex              false
port config -advertise10HalfDuplex              false
port config -advertise1000FullDuplex            false
port config -portMode                           portEthernetMode
port config -enableDataCenterMode               false
port config -dataCenterMode                     eightPriorityTrafficMapping
port config -flowControlType                    ieee8023x
port config -pfcEnableValueListBitMatrix        ""
port config -pfcResponseDelayEnabled            0
port config -pfcResponseDelayQuanta             0
port config -rxTxMode                           gigNormal
port config -ignoreLink                         false
port config -advertiseAbilities                 portAdvertiseNone
port config -timeoutEnable                      true
port config -negotiateMasterSlave               0
port config -masterSlave                        portSlave
port config -pmaClock                           pmaClockAutoNegotiate
port config -enableSimulateCableDisconnect      false
port config -enableAutoDetectInstrumentation    false
port config -autoDetectInstrumentationMode      portAutoInstrumentationModeEndOfFrame
port config -enableRepeatableLastRandomPattern  false
port config -transmitClockDeviation             0
port config -transmitClockMode                  portClockInternal
port config -preEmphasis                        preEmphasis0
port config -transmitExtendedTimestamp          0
port config -operationModeList                  [list]
port config -MacAddress                         "00 de bb 00 00 01"
port config -DestMacAddress                     "00 de bb 00 00 02"
port config -name                               ""
port config -numAddresses                       1
port config -enableManualAutoNegotiate          false
port config -enablePhyPolling                   true
port config -enableTxRxSyncStatsMode            false
port config -txRxSyncInterval                   0
port config -enableTransparentDynamicRateChange false
port config -enableDynamicMPLSMode              false
port config -enablePortCpuFlowControl           false
port config -portCpuFlowControlDestAddr         "01 80 C2 00 00 01"
port config -portCpuFlowControlSrcAddr          "00 00 01 00 02 00"
port config -portCpuFlowControlPriority         "0 0 0 0 0 0 0 0"
port config -portCpuFlowControlType             0
port config -enableWanIFSStretch                false
port config -enableRestartStream                false
port config -enableRxNonIEEEPreamble            false
port config -enableRsFec                        false
port config -enableRsFecStats                   false
port config -enableLinkTraining                 false
port config -ieeeL1Defaults                     0
if {[port set $chassis $card $port]} {
	errorMsg "Error calling port set $chassis $card $port"
	set retCode $::TCL_ERROR
}

stat setDefault 
stat config -mode                               statNormal
stat config -enableValidStats                   false
stat config -enableProtocolServerStats          true
stat config -enableArpStats                     true
stat config -enablePosExtendedStats             true
stat config -enableDhcpStats                    false
stat config -enableDhcpV6Stats                  false
stat config -enableEthernetOamStats             false
stat config -enableFcoeStats                    false
stat config -fcoeRxSharedStatType1              statFcoeValidFrames
stat config -fcoeRxSharedStatType2              statFcoeValidFrames
stat config -enableLldpDcbxStats                false
stat config -enableBgpStats                     false
stat config -enableIcmpStats                    true
stat config -enableOspfStats                    false
stat config -enableIsisStats                    false
stat config -enableRsvpStats                    false
stat config -enableLdpStats                     false
stat config -enableIgmpStats                    false
stat config -enableOspfV3Stats                  false
stat config -enablePimsmStats                   false
stat config -enableMldStats                     false
stat config -enableStpStats                     false
stat config -enableEigrpStats                   false
stat config -enableBfdStats                     false
stat config -enableCfmStats                     false
stat config -enableLacpStats                    false
stat config -enableOamStats                     false
stat config -enableMplsTpStats                  false
stat config -enableElmiStats                    false
if {[stat set $chassis $card $port]} {
	errorMsg "Error calling stat set $chassis $card $port"
	set retCode $::TCL_ERROR
}

packetGroup setDefault 
packetGroup config -signatureOffset                    48
packetGroup config -signature                          "08 71 18 05"
packetGroup config -insertSignature                    false
packetGroup config -ignoreSignature                    false
packetGroup config -groupId                            0
packetGroup config -groupIdOffset                      52
packetGroup config -enableGroupIdMask                  true
packetGroup config -enableInsertPgid                   true
packetGroup config -groupIdMask                        61440
packetGroup config -latencyControl                     cutThrough
packetGroup config -measurementMode                    packetGroupModeLatency
packetGroup config -preambleSize                       8
packetGroup config -sequenceNumberOffset               44
packetGroup config -sequenceErrorThreshold             2
packetGroup config -insertSequenceSignature            false
packetGroup config -allocateUdf                        true
packetGroup config -enableSignatureMask                false
packetGroup config -signatureMask                      "00 00 00 00"
packetGroup config -enableRxFilter                     false
packetGroup config -headerFilter                       "00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"
packetGroup config -headerFilterMask                   "00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"
packetGroup config -enable128kBinMode                  false
packetGroup config -enableTimeBins                     false
packetGroup config -numPgidPerTimeBin                  32
packetGroup config -numTimeBins                        1
packetGroup config -timeBinDuration                    1000000
packetGroup config -enableLatencyBins                  false
packetGroup config -latencyBinList                     ""
packetGroup config -groupIdMode                        packetGroupCustom
packetGroup config -sequenceCheckingMode               seqThreshold
packetGroup config -multiSwitchedPathMode              seqSwitchedPathPGID
packetGroup config -pgidStatMode                       0
packetGroup config -enableLastBitTimeStamp             false
packetGroup config -seqAdvTrackingLateThreshold        1000
packetGroup config -enableReArmFirstTimeStamp          false
if {[packetGroup setRx $chassis $card $port]} {
	errorMsg "Error calling packetGroup setRx $chassis $card $port"
	set retCode $::TCL_ERROR
}


filter setDefault 
filter config -captureTriggerDA                   anyAddr
filter config -captureTriggerSA                   anyAddr
filter config -captureTriggerPattern              anyPattern
filter config -captureTriggerError                errAnyFrame
filter config -captureTriggerFrameSizeEnable      true
filter config -captureTriggerFrameSizeFrom        256
filter config -captureTriggerFrameSizeTo          512
filter config -captureTriggerCircuit              filterAnyCircuit
filter config -captureFilterDA                    anyAddr
filter config -captureFilterSA                    anyAddr
filter config -captureFilterPattern               anyPattern
filter config -captureFilterError                 errAnyFrame
filter config -captureFilterFrameSizeEnable       true
filter config -captureFilterFrameSizeFrom         512
filter config -captureFilterFrameSizeTo           1024
filter config -captureFilterCircuit               filterAnyCircuit
filter config -userDefinedStat1DA                 anyAddr
filter config -userDefinedStat1SA                 anyAddr
filter config -userDefinedStat1Pattern            anyPattern
filter config -userDefinedStat1Error              errAnyFrame
filter config -userDefinedStat1FrameSizeEnable    true
filter config -userDefinedStat1FrameSizeFrom      64
filter config -userDefinedStat1FrameSizeTo        128
filter config -userDefinedStat1Circuit            filterAnyCircuit
filter config -userDefinedStat2DA                 anyAddr
filter config -userDefinedStat2SA                 anyAddr
filter config -userDefinedStat2Pattern            anyPattern
filter config -userDefinedStat2Error              errAnyFrame
filter config -userDefinedStat2FrameSizeEnable    1
filter config -userDefinedStat2FrameSizeFrom      128
filter config -userDefinedStat2FrameSizeTo        256
filter config -userDefinedStat2Circuit            filterAnyCircuit
filter config -asyncTrigger1DA                    anyAddr
filter config -asyncTrigger1SA                    anyAddr
filter config -asyncTrigger1Pattern               anyPattern
filter config -asyncTrigger1Error                 errAnyFrame
filter config -asyncTrigger1FrameSizeEnable       true
filter config -asyncTrigger1FrameSizeFrom         1024
filter config -asyncTrigger1FrameSizeTo           1086
filter config -asyncTrigger1Circuit               filterAnyCircuit
filter config -asyncTrigger2DA                    anyAddr
filter config -asyncTrigger2SA                    anyAddr
filter config -asyncTrigger2Pattern               anyPattern
filter config -asyncTrigger2Error                 errAnyFrame
filter config -asyncTrigger2FrameSizeEnable       true
filter config -asyncTrigger2FrameSizeFrom         1086
filter config -asyncTrigger2FrameSizeTo           1516
filter config -asyncTrigger2Circuit               filterAnyCircuit
filter config -captureTriggerEnable               true
filter config -captureFilterEnable                true
filter config -userDefinedStat1Enable             true
filter config -userDefinedStat2Enable             true
filter config -asyncTrigger1Enable                true
filter config -asyncTrigger2Enable                true
filter config -userDefinedStat1PatternExpressionEnable false
filter config -userDefinedStat2PatternExpressionEnable false
filter config -captureTriggerPatternExpressionEnable false
filter config -captureFilterPatternExpressionEnable false
filter config -asyncTrigger1PatternExpressionEnable false
filter config -asyncTrigger2PatternExpressionEnable false
filter config -userDefinedStat1PatternExpression  ""
filter config -userDefinedStat2PatternExpression  ""
filter config -captureTriggerPatternExpression    ""
filter config -captureFilterPatternExpression     ""
filter config -asyncTrigger1PatternExpression     ""
filter config -asyncTrigger2PatternExpression     ""
if {[filter set $chassis $card $port]} {
	errorMsg "Error calling filter set $chassis $card $port"
	set retCode $::TCL_ERROR
}


filterPallette setDefault 
filterPallette config -DA1                                "00 00 00 00 00 00"
filterPallette config -DAMask1                            "00 00 00 00 00 00"
filterPallette config -DA2                                "00 00 00 00 00 00"
filterPallette config -DAMask2                            "00 00 00 00 00 00"
filterPallette config -SA1                                "00 00 00 00 00 00"
filterPallette config -SAMask1                            "00 00 00 00 00 00"
filterPallette config -SA2                                "00 00 00 00 00 00"
filterPallette config -SAMask2                            "00 00 00 00 00 00"
filterPallette config -pattern1                           "DE ED EF FE AC CA"
filterPallette config -patternMask1                       "00 00 00 00 00 00"
filterPallette config -pattern2                           00
filterPallette config -patternMask2                       00
filterPallette config -pattern3                           ""
filterPallette config -patternMask3                       ""
filterPallette config -pattern4                           ""
filterPallette config -patternMask4                       ""
filterPallette config -patternOffset1                     12
filterPallette config -patternOffset2                     12
filterPallette config -patternOffset3                     0
filterPallette config -patternOffset4                     0
filterPallette config -matchType1                         matchUser
filterPallette config -matchType2                         matchUser
filterPallette config -matchType3                         3
filterPallette config -matchType4                         3
filterPallette config -patternOffsetType1                 filterPalletteOffsetStartOfFrame
filterPallette config -patternOffsetType2                 filterPalletteOffsetStartOfFrame
filterPallette config -patternOffsetType3                 0
filterPallette config -patternOffsetType4                 0
filterPallette config -gfpErrorCondition                  gfpErrorsOr
filterPallette config -enableGfptHecError                 true
filterPallette config -enableGfpeHecError                 true
filterPallette config -enableGfpPayloadCrcError           true
filterPallette config -enableGfpBadFcsError               true
filterPallette config -circuitList                        ""
filterPallette config -range1Min                          64
filterPallette config -range1Max                          128
filterPallette config -range2Min                          128
filterPallette config -range2Max                          256
filterPallette config -range3Min                          1024
filterPallette config -range3Max                          1086
filterPallette config -range4Min                          1086
filterPallette config -range4Max                          1516
filterPallette config -range1MatchMinMaxOnly              0
filterPallette config -range2MatchMinMaxOnly              0
filterPallette config -range3MatchMinMaxOnly              0
filterPallette config -range4MatchMinMaxOnly              0
if {[filterPallette set $chassis $card $port]} {
	errorMsg "Error calling filterPallette set $chassis $card $port"
	set retCode $::TCL_ERROR
}


ipAddressTable setDefault 
ipAddressTable config -defaultGateway                     "0.0.0.0"
if {[ipAddressTable set $chassis $card $port]} {
	errorMsg "Error calling ipAddressTable set $chassis $card $port"
	set retCode $::TCL_ERROR
}


if {[interfaceTable select $chassis $card $port]} {
	errorMsg "Error calling interfaceTable select $chassis $card $port"
	set retCode $::TCL_ERROR
}

interfaceTable setDefault 
interfaceTable config -dhcpV4RequestRate                  0
interfaceTable config -dhcpV6RequestRate                  0
interfaceTable config -dhcpV4MaximumOutstandingRequests   100
interfaceTable config -dhcpV6MaximumOutstandingRequests   100
interfaceTable config -fcoeRequestRate                    500
interfaceTable config -fcoeNumRetries                     5
interfaceTable config -fcoeRetryInterval                  2000
interfaceTable config -fipVersion                         fipVersion1
interfaceTable config -enableFcfMac                       false
interfaceTable config -fcfMacCollectionTime               1000
interfaceTable config -enablePMacInFpma                   true
interfaceTable config -enableNameIdInVLANDiscovery        false
interfaceTable config -enableTargetLinkLayerAddrOption    false
interfaceTable config -enableAutoNeighborDiscovery        false
interfaceTable config -enableAutoArp                      false
if {[interfaceTable set]} {
	errorMsg "Error calling interfaceTable set"
	set retCode $::TCL_ERROR
}

interfaceTable clearAllInterfaces 
if {[interfaceTable write]} {
	errorMsg "Error calling interfaceTable write"
	set retCode $::TCL_ERROR
}


protocolServer setDefault 
protocolServer config -enableArpResponse                  false
protocolServer config -enablePingResponse                 false
if {[protocolServer set $chassis $card $port]} {
	errorMsg "Error calling protocolServer set $chassis $card $port"
	set retCode $::TCL_ERROR
}


oamPort setDefault 
oamPort config -enable                             false
oamPort config -macAddress                         "00 00 AB BA DE AD"
oamPort config -enableLoopback                     false
oamPort config -enableLinkEvents                   false
oamPort config -maxOamPduSize                      1518
oamPort config -oui                                "00 00 00"
oamPort config -vendorSpecificInformation          "00 00 00 00"
oamPort config -idleTimer                          5
oamPort config -enableOptionalTlv                  false
oamPort config -optionalTlvType                    254
oamPort config -optionalTlvValue                   ""
if {[oamPort set $chassis $card $port]} {
	errorMsg "Error calling oamPort set $chassis $card $port"
	set retCode $::TCL_ERROR
}

lappend portList [list $chassis $card $port]
ixWritePortsToHardware portList
ixCheckLinkState portList



###################################################################
######### Generating streams for all the ports from above #########
###################################################################


######### Chassis-172.16.174.131 Card-1  Port-1 #########

chassis get "172.16.174.131"
set chassis	  [chassis cget -id]
set card     1
set port     1
streamRegion get $chassis $card $port
if {[streamRegion enableGenerateWarningList  $chassis $card $port 0]} {
	errorMsg "Error calling streamRegion enableGenerateWarningList  $chassis $card $port 0"
	set retCode $::TCL_ERROR
}

set streamId 1

if {[port resetStreamProtocolStack $chassis $card $port]} {
	errorMsg "Error calling port resetStreamProtocolStack $chassis $card $port"
	set retCode $::TCL_ERROR
}

#  Stream 1
stream setDefault 
stream config -name                               ""
stream config -enable                             true
stream config -enableSuspend                      false
stream config -region                             0
stream config -numBursts                          1
stream config -numFrames                          100
stream config -ifg                                96.00000000000091
stream config -ifgType                            gapFixed
stream config -ifgMIN                             96.00000000000091
stream config -ifgMAX                             96.00000000000091
stream config -ibg                                96.00000000000091
stream config -enableIbg                          false
stream config -isg                                96.00000000000091
stream config -enableIsg                          false
stream config -gapUnit                            gapNanoSeconds
stream config -percentPacketRate                  100.0
stream config -fpsRate                            154130.70283600493
stream config -bpsRate                            975339087.5462391
stream config -rateMode                           streamRateModePercentRate
stream config -preambleSize                       8
stream config -preambleData                       "55 55 55 55 55 55 D5"
stream config -sa                                 "00 0C 29 AF 95 8B"
stream config -saRepeatCounter                    idle
stream config -saStep                             1
stream config -saMaskValue                        "00 00 00 00 00 00"
stream config -saMaskSelect                       "00 00 00 00 00 00"
stream config -enableSaContinueFromLastValue      false
stream config -da                                 "00 00 00 00 00 00"
stream config -daRepeatCounter                    idle
stream config -daStep                             1
stream config -daMaskValue                        "00 00 00 00 00 00"
stream config -daMaskSelect                       "00 00 00 00 00 00"
stream config -enableDaContinueFromLastValue      false
stream config -framesize                          901
stream config -frameSizeType                      sizeRandom
stream config -frameSizeMIN                       64
stream config -frameSizeMAX                       1518
stream config -frameSizeStep                      1
stream config -enableTimestamp                    true
stream config -fcs                                good
stream config -patternType                        incrByte
stream config -dataPattern                        x00010203
stream config -pattern                            "00 01 02 03"
stream config -frameType                          "FF FF"
stream config -numDA                              16
stream config -numSA                              16
stream config -dma                                advance
stream config -rxTriggerEnable                    false
stream config -asyncIntEnable                     true
stream config -loopCount                          1
stream config -returnToId                         1
stream config -enforceMinGap                      12
stream config -enableStatistic                    true
stream config -enableIncrFrameBurstOverride       false
stream config -enableDisparityError               false
stream config -forceDisableDataMangling           0
stream config -enableSourceInterface              false
stream config -sourceInterfaceDescription         ""
stream config -startTxDelayUnit                   4
stream config -startTxDelay                       0.0
stream config -priorityGroup                      priorityGroup0

protocol setDefault 
protocol config -name                               mac
protocol config -appName                            noType
protocol config -ethernetType                       noType
protocol config -enable802dot1qTag                  vlanNone
protocol config -enableISLtag                       false
protocol config -enableMPLS                         false
protocol config -enableMacSec                       false
protocol config -enableOAM                          false
protocol config -enableProtocolPad                  false




if {[port isValidFeature $chassis $card $port $::portFeatureTableUdf]} { 
	tableUdf setDefault
	tableUdf clearColumns
	if {[tableUdf set $chassis $card $port]} {
		errorMsg "Error calling tableUdf set $chassis $card $port"
		set retCode $::TCL_ERROR
	}

}


if {[port isValidFeature $chassis $card $port $::portFeatureRandomFrameSizeWeightedPair]} { 
	weightedRandomFramesize setDefault
	if {[weightedRandomFramesize set $chassis $card $port]} {
		errorMsg "Error calling weightedRandomFramesize set $chassis $card $port"
		set retCode $::TCL_ERROR
	}

}

if {[stream set $chassis $card $port $streamId]} {
	errorMsg "Error calling stream set $chassis $card $port $streamId"
	set retCode $::TCL_ERROR
}

udf setDefault 
udf config -repeat                             1
udf config -continuousCount                    true
udf config -initval                            {00 00 00 00 }
udf config -updown                             uuuu
udf config -cascadeType                        udfCascadeNone
udf config -step                               1
packetGroup setDefault 
packetGroup config -signatureOffset                    48
packetGroup config -signature                          "08 71 18 05"
packetGroup config -insertSignature                    true
packetGroup config -ignoreSignature                    false
packetGroup config -groupId                            1999
packetGroup config -groupIdOffset                      52
packetGroup config -enableGroupIdMask                  false
packetGroup config -enableInsertPgid                   true
packetGroup config -groupIdMask                        0
packetGroup config -latencyControl                     cutThrough
packetGroup config -measurementMode                    packetGroupModeLatency
packetGroup config -preambleSize                       8
packetGroup config -sequenceNumberOffset               44
packetGroup config -sequenceErrorThreshold             2
packetGroup config -insertSequenceSignature            false
packetGroup config -allocateUdf                        true
packetGroup config -enableSignatureMask                false
packetGroup config -signatureMask                      "00 00 00 00"
packetGroup config -enableRxFilter                     false
packetGroup config -headerFilter                       "00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"
packetGroup config -headerFilterMask                   "00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"
packetGroup config -enable128kBinMode                  false
packetGroup config -enableTimeBins                     false
packetGroup config -numPgidPerTimeBin                  32
packetGroup config -numTimeBins                        10
packetGroup config -timeBinDuration                    1000000
packetGroup config -enableLatencyBins                  false
packetGroup config -latencyBinList                     ""
packetGroup config -groupIdMode                        packetGroupCustom
packetGroup config -sequenceCheckingMode               seqThreshold
packetGroup config -multiSwitchedPathMode              seqSwitchedPathPGID
packetGroup config -pgidStatMode                       0
packetGroup config -enableLastBitTimeStamp             false
packetGroup config -seqAdvTrackingLateThreshold        1000
packetGroup config -enableReArmFirstTimeStamp          false
if {[packetGroup setTx $chassis $card $port $streamId]} {
	errorMsg "Error calling packetGroup setTx $chassis $card $port $streamId"
	set retCode $::TCL_ERROR
}

incr streamId
if {[port resetStreamProtocolStack $chassis $card $port]} {
	errorMsg "Error calling port resetStreamProtocolStack $chassis $card $port"
	set retCode $::TCL_ERROR
}

#  Stream 2
stream setDefault 
stream config -name                               ""
stream config -enable                             true
stream config -enableSuspend                      false
stream config -region                             0
stream config -numBursts                          1
stream config -numFrames                          100
stream config -ifg                                96.00000000000091
stream config -ifgType                            gapFixed
stream config -ifgMIN                             96.00000000000091
stream config -ifgMAX                             96.00000000000091
stream config -ibg                                96.00000000000091
stream config -enableIbg                          false
stream config -isg                                96.00000000000091
stream config -enableIsg                          false
stream config -gapUnit                            gapNanoSeconds
stream config -percentPacketRate                  100.0
stream config -fpsRate                            154130.70283600493
stream config -bpsRate                            975339087.5462391
stream config -rateMode                           streamRateModePercentRate
stream config -preambleSize                       8
stream config -preambleData                       "55 55 55 55 55 55 D5"
stream config -sa                                 "00 0C 29 AF 95 8B"
stream config -saRepeatCounter                    idle
stream config -saStep                             1
stream config -saMaskValue                        "00 00 00 00 00 00"
stream config -saMaskSelect                       "00 00 00 00 00 00"
stream config -enableSaContinueFromLastValue      false
stream config -da                                 "00 00 00 00 00 00"
stream config -daRepeatCounter                    idle
stream config -daStep                             1
stream config -daMaskValue                        "00 00 00 00 00 00"
stream config -daMaskSelect                       "00 00 00 00 00 00"
stream config -enableDaContinueFromLastValue      false
stream config -framesize                          1415
stream config -frameSizeType                      sizeRandom
stream config -frameSizeMIN                       64
stream config -frameSizeMAX                       1518
stream config -frameSizeStep                      1
stream config -enableTimestamp                    true
stream config -fcs                                good
stream config -patternType                        incrByte
stream config -dataPattern                        x00010203
stream config -pattern                            "00 01 02 03"
stream config -frameType                          "FF FF"
stream config -numDA                              16
stream config -numSA                              16
stream config -dma                                gotoFirst
stream config -rxTriggerEnable                    false
stream config -asyncIntEnable                     true
stream config -loopCount                          1
stream config -returnToId                         1
stream config -enforceMinGap                      12
stream config -enableStatistic                    true
stream config -enableIncrFrameBurstOverride       false
stream config -enableDisparityError               false
stream config -forceDisableDataMangling           0
stream config -enableSourceInterface              false
stream config -sourceInterfaceDescription         ""
stream config -startTxDelayUnit                   4
stream config -startTxDelay                       0.0
stream config -priorityGroup                      priorityGroup0

protocol setDefault 
protocol config -name                               mac
protocol config -appName                            noType
protocol config -ethernetType                       noType
protocol config -enable802dot1qTag                  vlanNone
protocol config -enableISLtag                       false
protocol config -enableMPLS                         false
protocol config -enableMacSec                       false
protocol config -enableOAM                          false
protocol config -enableProtocolPad                  false




if {[port isValidFeature $chassis $card $port $::portFeatureTableUdf]} { 
	tableUdf setDefault
	tableUdf clearColumns
	if {[tableUdf set $chassis $card $port]} {
		errorMsg "Error calling tableUdf set $chassis $card $port"
		set retCode $::TCL_ERROR
	}

}


if {[port isValidFeature $chassis $card $port $::portFeatureRandomFrameSizeWeightedPair]} { 
	weightedRandomFramesize setDefault
	if {[weightedRandomFramesize set $chassis $card $port]} {
		errorMsg "Error calling weightedRandomFramesize set $chassis $card $port"
		set retCode $::TCL_ERROR
	}

}

if {[stream set $chassis $card $port $streamId]} {
	errorMsg "Error calling stream set $chassis $card $port $streamId"
	set retCode $::TCL_ERROR
}

udf setDefault 
udf config -repeat                             1
udf config -continuousCount                    true
udf config -initval                            {00 00 00 00 }
udf config -updown                             uuuu
udf config -cascadeType                        udfCascadeNone
udf config -step                               1
packetGroup setDefault 
packetGroup config -signatureOffset                    48
packetGroup config -signature                          "08 71 18 05"
packetGroup config -insertSignature                    true
packetGroup config -ignoreSignature                    false
packetGroup config -groupId                            2000
packetGroup config -groupIdOffset                      52
packetGroup config -enableGroupIdMask                  false
packetGroup config -enableInsertPgid                   true
packetGroup config -groupIdMask                        0
packetGroup config -latencyControl                     cutThrough
packetGroup config -measurementMode                    packetGroupModeLatency
packetGroup config -preambleSize                       8
packetGroup config -sequenceNumberOffset               44
packetGroup config -sequenceErrorThreshold             2
packetGroup config -insertSequenceSignature            false
packetGroup config -allocateUdf                        true
packetGroup config -enableSignatureMask                false
packetGroup config -signatureMask                      "00 00 00 00"
packetGroup config -enableRxFilter                     false
packetGroup config -headerFilter                       "00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"
packetGroup config -headerFilterMask                   "00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"
packetGroup config -enable128kBinMode                  false
packetGroup config -enableTimeBins                     false
packetGroup config -numPgidPerTimeBin                  32
packetGroup config -numTimeBins                        10
packetGroup config -timeBinDuration                    1000000
packetGroup config -enableLatencyBins                  false
packetGroup config -latencyBinList                     ""
packetGroup config -groupIdMode                        packetGroupCustom
packetGroup config -sequenceCheckingMode               seqThreshold
packetGroup config -multiSwitchedPathMode              seqSwitchedPathPGID
packetGroup config -pgidStatMode                       0
packetGroup config -enableLastBitTimeStamp             false
packetGroup config -seqAdvTrackingLateThreshold        1000
packetGroup config -enableReArmFirstTimeStamp          false
if {[packetGroup setTx $chassis $card $port $streamId]} {
	errorMsg "Error calling packetGroup setTx $chassis $card $port $streamId"
	set retCode $::TCL_ERROR
}

incr streamId
streamRegion generateWarningList $chassis $card $port

######### Chassis-172.16.174.131 Card-2  Port-1 #########

set card     2
set port     1
streamRegion get $chassis $card $port
if {[streamRegion enableGenerateWarningList  $chassis $card $port 0]} {
	errorMsg "Error calling streamRegion enableGenerateWarningList  $chassis $card $port 0"
	set retCode $::TCL_ERROR
}

set streamId 1

if {[port resetStreamProtocolStack $chassis $card $port]} {
	errorMsg "Error calling port resetStreamProtocolStack $chassis $card $port"
	set retCode $::TCL_ERROR
}

#  Stream 1
stream setDefault 
stream config -name                               ""
stream config -enable                             true
stream config -enableSuspend                      false
stream config -region                             0
stream config -numBursts                          1
stream config -numFrames                          100
stream config -ifg                                96.0
stream config -ifgType                            gapFixed
stream config -ifgMIN                             96.0
stream config -ifgMAX                             96.0
stream config -ibg                                96.0
stream config -enableIbg                          false
stream config -isg                                96.0
stream config -enableIsg                          false
stream config -gapUnit                            gapNanoSeconds
stream config -percentPacketRate                  99.99999999999999
stream config -fpsRate                            81274.38231469439
stream config -bpsRate                            986996098.8296487
stream config -rateMode                           streamRateModePercentRate
stream config -preambleSize                       8
stream config -preambleData                       "55 55 55 55 55 55 D5"
stream config -sa                                 "00 0C 29 6C E9 58"
stream config -saRepeatCounter                    idle
stream config -saStep                             1
stream config -saMaskValue                        "00 00 00 00 00 00"
stream config -saMaskSelect                       "00 00 00 00 00 00"
stream config -enableSaContinueFromLastValue      false
stream config -da                                 "00 00 00 00 00 00"
stream config -daRepeatCounter                    idle
stream config -daStep                             1
stream config -daMaskValue                        "00 00 00 00 00 00"
stream config -daMaskSelect                       "00 00 00 00 00 00"
stream config -enableDaContinueFromLastValue      false
stream config -framesize                          1518
stream config -frameSizeType                      sizeFixed
stream config -frameSizeMIN                       1518
stream config -frameSizeMAX                       1518
stream config -frameSizeStep                      1
stream config -enableTimestamp                    false
stream config -fcs                                good
stream config -patternType                        incrByte
stream config -dataPattern                        x00010203
stream config -pattern                            "00 01 02 03"
stream config -frameType                          "FF FF"
stream config -numDA                              16
stream config -numSA                              16
stream config -dma                                contPacket
stream config -rxTriggerEnable                    false
stream config -asyncIntEnable                     true
stream config -loopCount                          1
stream config -returnToId                         1
stream config -enforceMinGap                      12
stream config -enableStatistic                    true
stream config -enableIncrFrameBurstOverride       false
stream config -enableDisparityError               false
stream config -forceDisableDataMangling           0
stream config -enableSourceInterface              false
stream config -sourceInterfaceDescription         ""
stream config -startTxDelayUnit                   4
stream config -startTxDelay                       0.0
stream config -priorityGroup                      priorityGroup0

protocol setDefault 
protocol config -name                               mac
protocol config -appName                            noType
protocol config -ethernetType                       noType
protocol config -enable802dot1qTag                  vlanNone
protocol config -enableISLtag                       false
protocol config -enableMPLS                         false
protocol config -enableMacSec                       false
protocol config -enableOAM                          false
protocol config -enableProtocolPad                  false




if {[port isValidFeature $chassis $card $port $::portFeatureTableUdf]} { 
	tableUdf setDefault
	tableUdf clearColumns
	if {[tableUdf set $chassis $card $port]} {
		errorMsg "Error calling tableUdf set $chassis $card $port"
		set retCode $::TCL_ERROR
	}

}


if {[port isValidFeature $chassis $card $port $::portFeatureRandomFrameSizeWeightedPair]} { 
	weightedRandomFramesize setDefault
	if {[weightedRandomFramesize set $chassis $card $port]} {
		errorMsg "Error calling weightedRandomFramesize set $chassis $card $port"
		set retCode $::TCL_ERROR
	}

}

if {[stream set $chassis $card $port $streamId]} {
	errorMsg "Error calling stream set $chassis $card $port $streamId"
	set retCode $::TCL_ERROR
}

incr streamId
streamRegion generateWarningList $chassis $card $port
ixWriteConfigToHardware portList -noProtocolServer
